services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - ./backend/.env
    volumes:
      - /app/node_modules
      - ./backend:/app
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      # - redis
      - postgres
  # redis: # Name of container
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes: 
  #     - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "docker-nest-postgres"
      POSTGRES_USER: "itrustss"
      POSTGRES_PASSWORD: "iTrustss@@"
    ports: 
      - '5432:5432'
    volumes:
      - docker-note-postgres:/var/lib/postgresql/data

volumes:
  docker-note-postgres:
  # redis:
  #   driver: local