###Create a New Note
POST http://localhost:3000/notes
content-type: application/json

{
     "title":"title2",
    "content":"this is ght dggfs dgfsd sdfg sdfg"
}

###Get all Notes
GET http://localhost:3000/notes
content-type: application/json



###update Note
PATCH  http://localhost:3000/notes/2
content-type: application/json

{
    "title":"title changed",
    "content":"content changed sdfjdslfj ldsjflkjds lfs daf"
}



###Delete Note
DELETE  http://localhost:3000/notes/2
content-type: application/json

