###Create a New Note
POST http://localhost:3000/notes
content-type: application/json

{
    "noteText":"this is ght dggfs dgfsd sdfg sdfg"
}

###Get all Notes
GET http://localhost:3000/notes
content-type: application/json

# {
#     "noteText":"this is tesinggsjslflsj"
# }


###update Note
PATCH  http://localhost:3000/notes/14
content-type: application/json

{
    "noteText":"this is t fdasf aewea rar"
}



###Delete Note
DELETE  http://localhost:3000/notes/14
content-type: application/json

